### ISSUE TITLE
Questions about Jupyter notebook

### ISSUE THREAD

**Issue by AmeliaMN** [SmithCollege-SDS/tidy-islr#3]
@jcrouser I am going to need a tutorial on working smarter in Jupyter. It is driving me crazy that my key commands don't work! I'm also wishing for more customization. For example, in knitr documents (RMarkdown or LaTeX with R code chunks) I know how to get messages not to print-- in the code chunk options I will put message=FALSE. Is there something similar for cells?

**Comment by robertmitchellv** [comment]
Do you think there would be any interest in converting the Jupyter notebooks to `Rmd_notebook`'s for people more comfortable working in RStudio?  The benefit is that once everything is finished they can be easily converted into `output: html_document` in the yaml and knit into an Rmarkdown website with `rmarkdown::render_site()`.

**Comment by AmeliaMN** [comment]
I am a big proponent of Rmd, but @jcrouser teaches in Jupyter, so it makes sense to leave it that way for now. If there was a pandoc/knitr function to convert from one to the other we wouldn't have to decide. @yihui, do you know off the top of your head?

**Comment by yihui** [comment]
Coincidently @DanielHadley just pinged me on Twitter https://twitter.com/danielphadley/status/775457012586950656 and I thought a converter existed, but the blog post was not about the converter (lovely blog post, though).

Anyway, I did a quick google search, and found @chronitis' work: https://github.com/chronitis/ipyrmd

**Comment by jcrouser** [comment]
Used ipyrmd to convert to .Rmd. There's no need to stay with Jupyter for my sake, I'm fine using Rmd.

**Comment by chronitis** [comment]
Good to know it is being used. I know the repository looks a bit quiet at the moment, but if you find any issues please let me know.
